from telegram.ext import ConversationHandler


FIND_PHOTO = range(1)
FIND_PHOTO, STYLE_SELECT, STYLE_DETAIL = range(3)
FIND_PHOTO, STYLE_SELECT, STYLE_DETAIL, MENU_CHOICE = range(4)
FIND_PHOTO, STYLE_SELECT, STYLE_DETAIL, MENU_CHOICE, GENERAL_RECOMMEND = range(5)
(
    FIND_PHOTO,
    STYLE_SELECT,
    STYLE_DETAIL,
    MENU_CHOICE,
    GENERAL_RECOMMEND,
    GENDER_SELECT,
) = range(6)
